return {
	icons = {
		diagnostics = {
			Error = "ﮊ",
			Warn = "",
			Hint = "",
			Info = "",
		},
		git = {
			added = " ",
			modified = " ",
			removed = " ",
		},
		statusline = {
			-- 
			vertical_bar_thin = "│",
			vertical_bar = "┃",
			block = "█",
			----------------------------------------------
			left = "",
			left_filled = "",
			right = "",
			right_filled = "",
			----------------------------------------------
			slant_left = "",
			slant_left_thin = "",
			slant_right = "",
			slant_right_thin = "",
			----------------------------------------------
			slant_left_2 = "",
			slant_left_2_thin = "",
			slant_right_2 = "",
			slant_right_2_thin = "",
			----------------------------------------------
			left_rounded = "",
			left_rounded_thin = "",
			right_rounded = "",
			right_rounded_thin = "",
			----------------------------------------------
			trapezoid_left = "",
			trapezoid_right = "",
			----------------------------------------------
			line_number = "",
			column_number = "",
		},
		kinds = {
			Array = " ",
			Boolean = " ",
			Class = " ",
			Color = " ",
			Constant = " ",
			Constructor = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = " ",
			File = " ",
			Folder = " ",
			Function = " ",
			Interface = " ",
			Key = " ",
			Keyword = " ",
			Method = " ",
			Module = " ",
			Namespace = " ",
			Null = "ﳠ ",
			Number = " ",
			Object = " ",
			Operator = " ",
			Package = " ",
			Property = " ",
			Reference = " ",
			Snippet = " ",
			String = " ",
			Struct = " ",
			Text = " ",
			TypeParameter = " ",
			Unit = " ",
			Value = " ",
			Variable = " ",
		},
	},
}
